var currencies = [
    {key:"AED",name:"UAE Dirham",countries:["AE"]},
	{key:"AFN",name:"Afghani",countries:["AF"]},
	{key:"ALL",name:"Lek",countries:["AL"]},
	{key:"AMD",name:"Armenian Dram",countries:["AM"]},
	{key:"ANG",name:"Netherlands Antillean Guilder",countries:["CW","SX"]},
	{key:"AOA",name:"Kwanza",countries:["AO"]},
	{key:"ARS",name:"Argentine Peso",countries:["AR"]},
	{key:"AUD",name:"Australian Dollar",countries:["AU","CX","CC","HM","KI","NR","NF","TV"]},
	{key:"AWG",name:"Aruban Florin",countries:["AW"]},
	{key:"AZN",name:"Azerbaijanian Manat",countries:["AZ"]},
	{key:"BAM",name:"Convertible Mark",countries:["BA"]},
	{key:"BBD",name:"Barbados Dollar",countries:["BB"]},
	{key:"BDT",name:"Taka",countries:["BD"]},
	{key:"BGN",name:"Bulgarian Lev",countries:["BG"]},
	{key:"BHD",name:"Bahraini Dinar",countries:["BH"]},
	{key:"BIF",name:"Burundi Franc",countries:["BI"]},
	{key:"BMD",name:"Bermudian Dollar",countries:["BM"]},
	{key:"BND",name:"Brunei Dollar",countries:["BN"]},
	{key:"BOB",name:"Boliviano",countries:["BO"]},
	{key:"BRL",name:"Brazilian Real",countries:["BR"]},
	{key:"BSD",name:"Bahamian Dollar",countries:["BS"]},
	{key:"BTN",name:"Ngultrum",countries:["BT"]},
	{key:"BWP",name:"Pula",countries:["BW"]},
	{key:"BYR",name:"Belarussian Ruble",countries:["BY"]},
	{key:"BZD",name:"Belize Dollar",countries:["BZ"]},
	{key:"CAD",name:"Canadian Dollar",countries:["CA"]},
	{key:"CDF",name:"Congolese Franc",countries:["CD"]},
	{key:"CHF",name:"Swiss Franc",countries:["LI","CH"]},
	{key:"CLP",name:"Chilean Peso",countries:["CL"]},
	{key:"CNY",name:"Yuan Renminbi",countries:["CN"]},
	{key:"COP",name:"Colombian Peso",countries:["CO"]},
	{key:"CRC",name:"Costa Rican Colon",countries:["CR"]},
	{key:"CUC",name:"Peso Convertible",countries:["CU"]},
	{key:"CUP",name:"Cuban Peso",countries:["CU"]},
	{key:"CVE",name:"Cape Verde Escudo",countries:["CV"]},
	{key:"CZK",name:"Czech Koruna",countries:["CZ"]},
	{key:"DJF",name:"Djibouti Franc",countries:["DJ"]},
	{key:"DKK",name:"Danish Krone",countries:["DK","FO","GL"]},
	{key:"DOP",name:"Dominican Peso",countries:["DO"]},
	{key:"DZD",name:"Algerian Dinar",countries:["DZ"]},
	{key:"EGP",name:"Egyptian Pound",countries:["EG"]},
	{key:"ERN",name:"Nakfa",countries:["ER"]},
	{key:"ETB",name:"Ethiopian Birr",countries:["ET"]},
	{key:"EUR",name:"Euro",countries:["AX","AD","AT","BE","CY","EE","FI","FR","GF","TF","DE","GR","GP","IE","IT","LU","MT","MQ","YT","MC","ME","NL","PT","RE","BL","MF","PM","SM","SK","SI","ES","VA"]},
	{key:"FJD",name:"Fiji Dollar",countries:["FJ"]},
	{key:"FKP",name:"Falkland Islands Pound",countries:["FK"]},
	{key:"GBP",name:"Pound Sterling",countries:["GG","IM","JE","GB"]},
	{key:"GEL",name:"Lari",countries:["GE"]},
	{key:"GHS",name:"Ghana Cedi",countries:["GH"]},
	{key:"GIP",name:"Gibraltar Pound",countries:["GI"]},
	{key:"GMD",name:"Dalasi",countries:["GM"]},
	{key:"GNF",name:"Guinea Franc",countries:["GN"]},
	{key:"GTQ",name:"Quetzal",countries:["GT"]},
	{key:"GYD",name:"Guyana Dollar",countries:["GY"]},
	{key:"HKD",name:"Hong Kong Dollar",countries:["HK"]},
	{key:"HNL",name:"Lempira",countries:["HN"]},
	{key:"HRK",name:"Croatian Kuna",countries:["HR"]},
	{key:"HTG",name:"Gourde",countries:["HT"]},
	{key:"HUF",name:"Forint",countries:["HU"]},
	{key:"IDR",name:"Rupiah",countries:["ID"]},
	{key:"ILS",name:"New Israeli Sheqel",countries:["IL"]},
	{key:"INR",name:"Indian Rupee",countries:["BT","IN"]},
	{key:"IQD",name:"Iraqi Dinar",countries:["IQ"]},
	{key:"IRR",name:"Iranian Rial",countries:["IR"]},
	{key:"ISK",name:"Iceland Krona",countries:["IS"]},
	{key:"JMD",name:"Jamaican Dollar",countries:["JM"]},
	{key:"JOD",name:"Jordanian Dinar",countries:["JO"]},
	{key:"JPY",name:"Yen",countries:["JP"]},
	{key:"KES",name:"Kenyan Shilling",countries:["KE"]},
	{key:"KGS",name:"Som",countries:["KG"]},
	{key:"KHR",name:"Riel",countries:["KH"]},
	{key:"KMF",name:"Comoro Franc",countries:["KM"]},
	{key:"KPW",name:"North Korean Won",countries:["KP"]},
	{key:"KRW",name:"Won",countries:["KR"]},
	{key:"KWD",name:"Kuwaiti Dinar",countries:["KW"]},
	{key:"KYD",name:"Cayman Islands Dollar",countries:["KY"]},
	{key:"KZT",name:"Tenge",countries:["KZ"]},
	{key:"LAK",name:"Kip",countries:["LA"]},
	{key:"LBP",name:"Lebanese Pound",countries:["LB"]},
	{key:"LKR",name:"Sri Lanka Rupee",countries:["LK"]},
	{key:"LRD",name:"Liberian Dollar",countries:["LR"]},
	{key:"LSL",name:"Loti",countries:["LS"]},
	{key:"LTL",name:"Lithuanian Litas",countries:["LT"]},
	{key:"LVL",name:"Latvian Lats",countries:["LV"]},
	{key:"LYD",name:"Libyan Dinar",countries:["LY"]},
	{key:"MAD",name:"Moroccan Dirham",countries:["MA","EH"]},
	{key:"MDL",name:"Moldovan Leu",countries:["MD"]},
	{key:"MGA",name:"Malagasy Ariary",countries:["MG"]},
	{key:"MKD",name:"Denar",countries:["MK"]},
	{key:"MMK",name:"Kyat",countries:["MM"]},
	{key:"MNT",name:"Tugrik",countries:["MN"]},
	{key:"MOP",name:"Pataca",countries:["MO"]},
	{key:"MRO",name:"Ouguiya",countries:["MR"]},
	{key:"MUR",name:"Mauritius Rupee",countries:["MU"]},
	{key:"MVR",name:"Rufiyaa",countries:["MV"]},
	{key:"MWK",name:"Kwacha",countries:["MW"]},
	{key:"MXN",name:"Mexican Peso",countries:["MX"]},
	{key:"MYR",name:"Malaysian Ringgit",countries:["MY"]},
	{key:"MZN",name:"Mozambique Metical",countries:["MZ"]},
	{key:"NAD",name:"Namibia Dollar",countries:["NA"]},
	{key:"NGN",name:"Naira",countries:["NG"]},
	{key:"NIO",name:"Cordoba Oro",countries:["NI"]},
	{key:"NOK",name:"Norwegian Krone",countries:["BV","NO","SJ"]},
	{key:"NPR",name:"Nepalese Rupee",countries:["NP"]},
	{key:"NZD",name:"New Zealand Dollar",countries:["CK","NZ","NU","PN","TK"]},
	{key:"OMR",name:"Rial Omani",countries:["OM"]},
	{key:"PAB",name:"Balboa",countries:["PA"]},
	{key:"PEN",name:"Nuevo Sol",countries:["PE"]},
	{key:"PGK",name:"Kina",countries:["PG"]},
	{key:"PHP",name:"Philippine Peso",countries:["PH"]},
	{key:"PKR",name:"Pakistan Rupee",countries:["PK"]},
	{key:"PLN",name:"Zloty",countries:["PL"]},
	{key:"PYG",name:"Guarani",countries:["PY"]},
	{key:"QAR",name:"Qatari Rial",countries:["QA"]},
	{key:"RON",name:"New Romanian Leu",countries:["RO"]},
	{key:"RSD",name:"Serbian Dinar",countries:["RS"]},
	{key:"RUB",name:"Russian Ruble",countries:["RU"]},
	{key:"RWF",name:"Rwanda Franc",countries:["RW"]},
	{key:"SAR",name:"Saudi Riyal",countries:["SA"]},
	{key:"SBD",name:"Solomon Islands Dollar",countries:["SB"]},
	{key:"SCR",name:"Seychelles Rupee",countries:["SC"]},
	{key:"SDG",name:"Sudanese Pound",countries:["SD"]},
	{key:"SEK",name:"Swedish Krona",countries:["SE"]},
	{key:"SGD",name:"Singapore Dollar",countries:["SG"]},
	{key:"SHP",name:"Saint Helena Pound",countries:["SH"]},
	{key:"SLL",name:"Leone",countries:["SL"]},
	{key:"SOS",name:"Somali Shilling",countries:["SO"]},
	{key:"SRD",name:"Surinam Dollar",countries:["SR"]},
	{key:"SSP",name:"South Sudanese Pound",countries:["SS"]},
	{key:"STD",name:"Dobra",countries:["ST"]},
	{key:"SVC",name:"El Salvador Colon",countries:["SV"]},
	{key:"SYP",name:"Syrian Pound",countries:["SY"]},
	{key:"SZL",name:"Lilangeni",countries:["SZ"]},
	{key:"THB",name:"Baht",countries:["TH"]},
	{key:"TJS",name:"Somoni",countries:["TJ"]},
	{key:"TMT",name:"Turkmenistan New Manat",countries:["TM"]},
	{key:"TND",name:"Tunisian Dinar",countries:["TN"]},
	{key:"TOP",name:"Pa'anga",countries:["TO"]},
	{key:"TRY",name:"Turkish Lira",countries:["TR"]},
	{key:"TTD",name:"Trinidad and Tobago Dollar",countries:["TT"]},
	{key:"TWD",name:"New Taiwan Dollar",countries:["TW"]},
	{key:"TZS",name:"Tanzanian Shilling",countries:["TZ"]},
	{key:"UAH",name:"Hryvnia",countries:["UA"]},
	{key:"UGX",name:"Uganda Shilling",countries:["UG"]},
	{key:"USD",name:"US Dollar",countries:["AS","BQ","IO","EC","SV","GU","HT","MH","FM","MP","PW","PA","PR","TL","TC","US","UM","VG","VI"]},
	{key:"UYU",name:"Peso Uruguayo",countries:["UY"]},
	{key:"UZS",name:"Uzbekistan Sum",countries:["UZ"]},
	{key:"VEF",name:"Bolivar",countries:["VE"]},
	{key:"VND",name:"Dong",countries:["VN"]},
	{key:"VUV",name:"Vatu",countries:["VU"]},
	{key:"WST",name:"Tala",countries:["WS"]},
	{key:"XAF",name:"CFA Franc BEAC",countries:["CM","CF","TD","CG","GQ","GA"]},
	{key:"XCD",name:"East Caribbean Dollar",countries:["AI","AG","DM","GD","MS","KN","LC","VC"]},
	{key:"XOF",name:"CFA Franc BCEAO",countries:["BJ","BF","CI","GW","ML","NE","SN","TG"]},
	{key:"XPF",name:"CFP Franc",countries:["PF","NC","WF"]},
	{key:"YER",name:"Yemeni Rial",countries:["YE"]},
	{key:"ZAR",name:"Rand",countries:["LS","NA","ZA"]},
	{key:"ZMW",name:"Zambian Kwacha",countries:["ZM"]},
	{key:"ZWL",name:"Zimbabwe Dollar",countries:["ZW"]}
];